spring:
  config:
    import: optional:file:${user.dir}/hub_service/.env[.properties]
  application:
    name: hub_service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

custom:
  jwt:
    exp-time:
      access: ${JWT_EXP_ACCESS}
      refresh: ${JWT_EXP_REFRESH}

    secrets:
      originkey: ${SECRET_ORIGIN_KEY}
      appkey: ${SECRET_APP_KEY}

server:
  port: ${HUB_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}