server:
  port: ${GATEWAY_SERVER_PORT}
spring:
  application:
    name: gateway-server
  config:
    import: optional:file:${user.dir}/gateway/.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-server
              uri: lb://user-server
              predicates:
                - Path=/v1/user/**,/v1/master/**

            - id: ai-service
              uri: lb://ai-server
              predicates:
                - Path=/v1/ai/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}


custom:
  jwt:
    secrets:
      appkey: ${SECRET_APPKEY}

