server:
  port: ${GATEWAY_SERVER_PORT}
spring:
  application:
    name: gateway-server
  config:
    import: optional:file:${user.dir}/gateway/.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/v1/user/**,/v1/master/**,/v1/delivery-admin/**

            - id: orchestrator-service
              uri: lb://orchestrator-service
              predicates:
                - Path=/v1/orchestrations/orders

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/v1/orders/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/v1/products/**

            - id: firm-service
              uri: lb://firm-service
              predicates:
                - Path=/v1/firms/**

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/v1/hubs/**,/v1/hub-infos/**,/v1/hub-routes/**

            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/v1/ai/**

            - id: slack-service
              uri: lb://slack-service
              predicates:
                - Path=/v1/slack/**


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}


custom:
  jwt:
    secrets:
      appkey: ${SECRET_APPKEY}

