spring:
  config:
    import: optional:file:${user.dir}/ai_service/.env[.properties]
  application:
    name: ai-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  # Spring AI (OpenAI)
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
    retry:
      max-attempts: 2
      backoff:
        initial-interval: 500ms

custom:
  service-url: ${AI_SERVICE_URL}

server:
  port: ${AI_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

clients:
  order:
    url: ${ORDER_SERVICE_URL}
  hub:
    url: ${HUB_SERVICE_URL}

# Spring Cloud OpenFeign 설정
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000
        loggerLevel: basic