spring:
  config:
    import: optional:file:${user.dir}/slack_service/.env[.properties]
  application:
    name: slack-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  # Slack
  slack:
    bot-token: ${SLACK_BOT_TOKEN}

server:
  port: ${SLACK_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

# 내부 서비스 호출용 커스텀 엔드포인트
clients:
  ai:
    url: ${AI_SERVICE_URL}

# Spring Cloud OpenFeign 설정
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000
        loggerLevel: basic